CREATE TABLE IF NOT EXISTS domestik_transfer (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kota_asal TEXT NOT NULL DEFAULT 'CGK',
  kota_tujuan TEXT NOT NULL,
  harga_modal NUMERIC(15, 2) NOT NULL DEFAULT 0,
  harga_jual NUMERIC(15, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO domestik_transfer (kota_asal, kota_tujuan, harga_modal, harga_jual) VALUES
  ('CGK', 'SAMARINDA', 0, 0),
  ('CGK', 'ATAMBUA', 0, 0),
  ('CGK', 'AEK GODANG', 0, 0),
  ('CGK', 'AMBON', 0, 0),
  ('CGK', 'ALOR', 0, 0),
  ('CGK', 'BANJARMASIN', 0, 0),
  ('CGK', 'BERAU', 0, 0),
  ('CGK', 'BIAK', 0, 0),
  ('CGK', 'BAJAWA', 0, 0),
  ('CGK', 'BENGKULU', 0, 0),
  ('CGK', 'BIMA', 0, 0),
  ('CGK', 'BALIKPAPAN', 0, 0),
  ('CGK', 'BATAM', 0, 0),
  ('CGK', 'ACEH', 0, 0),
  ('CGK', 'BATULICIN', 0, 0),
  ('CGK', 'M.BUNGO', 0, 0),
  ('CGK', 'BAU BAU', 0, 0),
  ('CGK', 'BANYUWANGI', 0, 0),
  ('CGK', 'YAHUKIMO', 0, 0),
  ('CGK', 'KEDIRI', 0, 0),
  ('CGK', 'JAMBI', 0, 0),
  ('CGK', 'JAYAPURA', 0, 0),
  ('CGK', 'DOBO', 0, 0),
  ('CGK', 'DENPASAR', 0, 0),
  ('CGK', 'SILANGIT', 0, 0),
  ('CGK', 'ENDE', 0, 0),
  ('CGK', 'ASMAT', 0, 0),
  ('CGK', 'FAK FAK', 0, 0),
  ('CGK', 'SIBOLGA', 0, 0),
  ('CGK', 'GALELA', 0, 0),
  ('CGK', 'G.SITOLI', 0, 0),
  ('CGK', 'GORONTALO', 0, 0),
  ('CGK', 'BARITO UTARA', 0, 0);
